### 회원가입 signup (USER)
POST localhost:8080/api/auth/signup?userRole=USER
Content-Type: application/json

{
  "username": "user45",
  "password": "Password123!",
  "name": "일반사용자",
  "userAddr" : "대한민국 어딘가"
}

### 회원가입 signup (BOOTCAMP)
POST localhost:8080/api/auth/signup?userRole=BOOTCAMP
Content-Type: application/json

{
  "username": "boot78",
  "password": "Password123!",
  "name": "부트캠프사용자",
  "userAddr" : "대한민국 어딘가",
  "campName" : "스파르타"
}

### 로그인 login
POST localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "user23",
  "password": "Password123!"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken)
    client.global.set("refreshToken", response.body.data.refreshToken)
%}

### 로그아웃 logout
POST localhost:8080/api/auth/logout
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 회원탈퇴 withdraw
POST localhost:8080/api/auth/resign
Content-Type: application/json
Authorization: Bearer {{accessToken}}