### 부트캠프 모집글 좋아요 추가
POST {{apiUrl}}/recruiments/1/likes
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 부트캠프 모집글 좋아요 취소
DELETE  {{apiUrl}}/recruiments/1/likes
Content-Type: application/json
Authorization: Bearer {{accessToken}}