### 부트캠프 모집글 좋아요 추가
POST {{apiUrl}}/recruiments/1/likes
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 부트캠프 모집글 좋아요 취소
DELETE  {{apiUrl}}/recruiments/1/likes
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 캠프 좋아요 추가
POST {{apiUrl}}/camps/1/like
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 캠프 좋아요 취소
DELETE  {{apiUrl}}/camps/1/like
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 캠프 좋아요 리스트 조회
GET {{apiUrl}}/camps/like/list
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 캠프 좋아요 개수 조회
GET {{apiUrl}}/camps/like/count
Content-Type: application/json
Authorization: Bearer {{accessToken}}