### 상세 필터 기능

### 트랙만 조회
GET {{apiUrl}}/ranks/filter?track=백엔드

### 수업 환경만 조회
GET {{apiUrl}}/ranks/filter?environment=오프라인

### 비용만 조회
GET {{apiUrl}}/ranks/filter?cost=사비

### 트랙과 수업 환경 포함 조회
GET {{apiUrl}}/ranks/filter?track=백엔드&environment=온라인

###트랙과 수업환경 & 비용 포함 조회
GET {{apiUrl}}/ranks/filter?track=백엔드&environment=온라인&cost=국비

