### 로그인 login
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "username": "boot12",
  "password": "Password123!"
}

> {%
  client.global.set("accessToken", response.body.data.accessToken)
  client.global.set("refreshToken", response.body.data.refreshToken)

  console.log('Response Status:', response.body.data.accessToken);
  console.log('Response Data:', response.body.data.refreshToken);
%}

### 모집글 작성
POST {{apiUrl}}/camps
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "모집글 제목",
  "process": "모집글 과정 소개글",
  "content": "모집글 내용",
  "place": "장소",
  "cost": "국비",
  "trek": "백엔드",
  "level": "초급",
  "campName" : "스파르타",
  "classTime": "월-금 오전9시~오후6시",
  "campStart": "2024-08-01",
  "campEnd": "2024-08-31",
  "recruitStart": "2024-07-01",
  "recruitEnd": "2024-07-31"
}

### 모집글 수정
PUT {{apiUrl}}/camps/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "모집글 제목 수정",
  "process": "모집글 과정 소개글 수정",
  "content": "모집글 내용 수정",
  "place": "소장",
  "cost": "유료",
  "trek": "프론트엔드",
  "level": "고급",
  "classTime": "토-일 오전10시~오후6시",
  "campStart": "2024-09-01",
  "campEnd": "2024-09-30",
  "recruitStart": "2024-08-01",
  "recruitEnd": "2024-08-31"
}

### 모집글 삭제
DELETE {{apiUrl}}/camps/2
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 모집글 전체 조회
GET {{apiUrl}}/camps
Content-Type: application/json

### 모집글 단건 조회
GET {{apiUrl}}/camps/3
Content-Type: application/json