### 로그인 login
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "username": "user12",
  "password": "Password123!"
}

> {%
  client.global.set("accessToken", response.body.data.accessToken)
  client.global.set("refreshToken", response.body.data.refreshToken)

  console.log('Response Status:', response.body.data.accessToken);
  console.log('Response Data:', response.body.data.refreshToken);
%}

### 리뷰 댓글의 대댓글 작성
POST {{apiUrl}}/reviews/1/comments/1/reply
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content" : "대댓글 작성"
}

### 리뷰 댓글의 대댓글 수정
PUT {{apiUrl}}/reviews/1/comments/1/reply/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content" : "대댓글 수정"
}

### 리뷰 댓글의 대댓글 삭제
DELETE {{apiUrl}}/reviews/1/comments/1/reply/2
Content-Type: application/json
Authorization: Bearer {{accessToken}}